from enum import Enum

class CategoryCode(str, Enum):
    TOURISM = "TOURISM"
    LEISURE = "LEISUR"
    CULTURAL_FACILITY = "CULTURAL_FACILITY"
    SHOPPING = "SHOPPING"
    ACCOMMODATION = "ACCOMMODATION"
    TRAVEL_COURSE = "TRAVEL_COURSE"
    RESTAURANT = "RESTAURANT"
    FESTIVAL = "FESTIVAL"
    DEFAULT = "DEFAULT"